<?php

namespace BC\PlatformBundle\Repository;

/**
 * CategoyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoyRepository extends \Doctrine\ORM\EntityRepository
{
}
